using Albatross.CodeAnalysis;
using Albatross.CodeGen;
using Albatross.CodeGen.CSharp;
using Albatross.CodeGen.CSharp.Declarations;
using Albatross.CodeGen.CSharp.Expressions;
using Albatross.CodeGen.CSharp.TypeConversions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using System.Linq;

namespace Albatross.Messaging.CodeGen {
	/// <summary>
	/// <code><![CDATA[
	/// namespace Sample.AutoGenerated {
	///		public static class CommandHandlerRegistration {
	///			public static IServiceCollection RegisterCommands(this IServiceCollection services, Func<ulong, object, IServiceProvider, string> getQueueName) {
	///				services.AddScoped<ICommandHandler<CommandHandlerExceptionTestCommand>, CommandHandlerExceptionTestCommandHandler>();
	///				services.AddCommand<CommandHandlerExceptionTestCommand>(new string[] { "CommandHandlerExceptionTestCommand" }, getQueueName);
	///				return services;
	///			}
	///		}
	/// }
	/// ]]></code>
	/// </summary>
	[Generator]
	public class CommandHandlerRegistrationGenerator : IIncrementalGenerator {
		class CommandHandlerInfo {
			public INamedTypeSymbol InterfaceType { get; }
			public INamedTypeSymbol ImplementationType { get; }
			public required INamedTypeSymbol CommandType { get; init; }
			public INamedTypeSymbol? ResponseType { get; init; }

			public CommandHandlerInfo(INamedTypeSymbol interfaceType, INamedTypeSymbol implementationType) {
				InterfaceType = interfaceType;
				ImplementationType = implementationType;
			}
		}


		private static IExpression CreateRegistrationExpression(Compilation compilation, CommandHandlerInfo info, DefaultTypeConverter typeConverter) {
			return new InvocationExpression {
				CallableExpression = new IdentifierNameExpression("services.AddScoped") {
					GenericArguments = new() {
						typeConverter.Convert(info.InterfaceType),
						typeConverter.Convert(info.ImplementationType),
					}
				},
			};
		}

		private static IExpression CreateAddCommandExpression(Compilation compilation, CommandHandlerInfo info, DefaultTypeConverter typeConverter) {
			var commandName = info.CommandType.GetFullName();
			return new InvocationExpression {
				CallableExpression = new IdentifierNameExpression("services.AddCommand") {
					GenericArguments = new() {
						typeConverter.Convert(info.CommandType),
						{  info.ResponseType != null, ()=> typeConverter.Convert(info.ResponseType!) }
					},
				},
				Arguments = {
					new ArrayExpression {
						Type = Defined.Types.String,
						Items = { new StringLiteralExpression(commandName) }
					},
					new IdentifierNameExpression("getQueueName"),
				}
			};
		}

		public void Initialize(IncrementalGeneratorInitializationContext context) {
			var compilationProvider = context.CompilationProvider.Select(static (x, _) => x);
			// The RootNamespace is the deterministic home for the generated CommandHandlerRegistration class.  It is
			// read from the project's build properties rather than derived from the handler classes in the compilation:
			// handlers spread over several namespaces would otherwise produce one registration class per namespace,
			// leaving the caller to guess which of them to import.
			var rootNamespaceProvider = context.AnalyzerConfigOptionsProvider.Select(static (provider, _) =>
				provider.GlobalOptions.TryGetValue("build_property.RootNamespace", out var ns) ? ns : null);
			var handlers = context.SyntaxProvider.CreateSyntaxProvider(
				predicate: static (node, _) => node is ClassDeclarationSyntax,
				transform: static (ctx, _) => {
					var model = ctx.SemanticModel;
					var symbol = model.GetDeclaredSymbol((ClassDeclarationSyntax)ctx.Node);
					if (symbol != null && symbol.IsConcreteClass()) {
						foreach (var interfaceType in symbol.AllInterfaces) {
							if (interfaceType.IsGenericType) {
								if (interfaceType.OriginalDefinition.Is(model.Compilation.ICommandHandlerGenericDefinition1()) ||
									interfaceType.OriginalDefinition.Is(model.Compilation.ICommandHandlerGenericDefinition2())) {
									return new CommandHandlerInfo(interfaceType, symbol) {
										CommandType = (INamedTypeSymbol)interfaceType.TypeArguments[0],
										ResponseType = interfaceType.TypeArguments.Length == 2 ? (INamedTypeSymbol)interfaceType.TypeArguments[1] : null,
									};
								}
							}
						}
					}
					return null;
				}
			).Where(static x => x != null);
			var aggregate = compilationProvider.Combine(rootNamespaceProvider).Combine(handlers.Collect());
			context.RegisterSourceOutput(aggregate, static (context, data) => {
				var (tuple, handlerSymbols) = data;
				var (compilation, rootNamespace) = tuple;
				if (handlerSymbols.Any()) {
					var typeConverter = new DefaultTypeConverter {
						UseQualifiedNames = true,
					};
					// Host the generated registration under <RootNamespace>.AutoGenerated so generated wiring stays in a
					// dedicated, clearly-named segment of the consuming assembly's own namespace.  Fall back to the
					// assembly name when RootNamespace is not supplied so we never emit into the global namespace.
					var baseNamespace = string.IsNullOrEmpty(rootNamespace) ? compilation.AssemblyName : rootNamespace;
					var @namespace = string.IsNullOrEmpty(baseNamespace) ? "AutoGenerated" : $"{baseNamespace}.AutoGenerated";
					var file = new FileDeclaration("CommandHandlerRegistration.g") {
						Namespace = new NamespaceExpression(@namespace),
						Classes = [
							new ClassDeclaration {
								IsStatic = true,
								AccessModifier = Defined.Keywords.Public,
								Name = new IdentifierNameExpression("CommandHandlerRegistration"),
								Methods = [
									new MethodDeclaration {
										Name = new IdentifierNameExpression("RegisterCommands"),
										IsStatic = true,
										AccessModifier = Defined.Keywords.Public,
										Parameters = new() {
											new ParameterDeclaration {
												Type = Defined.Types.IServiceCollection,
												Name = new IdentifierNameExpression("services"),
												UseThisKeyword = true,
											},
											new ParameterDeclaration {
												Type = new TypeExpression(new QualifiedIdentifierNameExpression("Func", Defined.Namespaces.System) {
													GenericArguments = [
														new TypeExpression("ulong"),
														Defined.Types.Object,
														new TypeExpression(new QualifiedIdentifierNameExpression("IServiceProvider", Defined.Namespaces.System)),
														Defined.Types.String,
													]
												}),
												Name = new IdentifierNameExpression("getQueueName"),
											}
										},
										Body = {
											{
												true, () => handlerSymbols.Select(x => CreateRegistrationExpression(compilation, x!, typeConverter))
											}, {
												true, () => handlerSymbols.Select(x => CreateAddCommandExpression(compilation, x!, typeConverter))
											},
											new ReturnExpression {
												Expression = new IdentifierNameExpression("services")
											}
										},
										ReturnType = Defined.Types.IServiceCollection,
									}
								]
							}
						]
					};
					var writer = new System.IO.StringWriter();
					file.Generate(writer);
					context.AddSource(file.FileName, writer.ToString());
				}
			});
		}
	}
}